#app
server:
    port: 80

#spring
spring:
  devtools:
    restart:
      enabled: false

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.95.213.244:3306/sweet?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: sweet-8888
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 2000
      testWhileIdle: true
  redis:
    host: 47.95.213.244
    port: 6301

#mybatis
mybatis-plus:
  mapper-locations: com/sweet/api/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sweet.api.entity
  typeEnumsPackage: com.sweet.api.constants.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging:
logging:
  config: classpath:log4j2.xml
  level.com.sweet.api.mapper: debug
